/**
 * Regenerates src/data/jewellerySnapshot.ts from live Shopify.
 *
 *   npx vite-node scripts/generate-jewellery-snapshot.ts
 *
 * Why this exists: JewelDetail could only draw a piece once the live catalogue
 * query resolved, unless the piece was in the hand-authored bundle — and that
 * bundle holds 21 of 56. Measured on the built site, prism-riviere-bracelet (the
 * #1 ad landing page, and the deepest stock) showed the "Loading piece" skeleton
 * for as long as Shopify took to answer: 1.3s with no added latency, 4s with 3s
 * added, while a bundled piece drew in ~260ms whatever Shopify did.
 *
 * Each entry is produced by the app's own fromShopify(), so first paint is the
 * same object live would build — nothing is hand-copied, nothing can drift in
 * shape. Pieces already hand-authored in jewellery.ts are skipped; their copy is
 * curated and must stay the authority.
 *
 * It also rewrites the handle list in src/data/jewelleryHandles.ts from the same
 * query. The two drifted apart once already — a piece switched to DRAFT stayed in
 * the handle list — and deriving both from one response is what stops that.
 *
 * Run it whenever pieces are added, repriced or restocked in Shopify. A stale
 * snapshot is corrected by live data within a second of load; a MISSING piece
 * is what brings the skeleton back, and productSnapshot.test.ts will fail if
 * any live jewellery handle is left uncovered.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fetchShopifyProducts } from "@/lib/shopify";
import { jewellery as authored } from "@/data/jewellery";
import { isJewelleryProduct } from "@/lib/isJewelleryProduct";
import { fromShopify } from "@/hooks/useLiveJewellery";

const nodes = await fetchShopifyProducts(250);
if (nodes.length < 20) {
  throw new Error(`Shopify returned only ${nodes.length} products — refusing to write a near-empty snapshot.`);
}
const known = new Set(authored.map((p) => p.handle));
const pieces = nodes
  .filter((n) => isJewelleryProduct(n) && !known.has(n.handle))
  .map((n, i) => fromShopify(n, authored.length + i));

const body = `/* GENERATED by scripts/generate-jewellery-snapshot.ts — do not edit by hand.
   Regenerate: npx vite-node scripts/generate-jewellery-snapshot.ts
   Generated ${new Date().toISOString()} from live Shopify: ${pieces.length} pieces.

   First-paint data for every live jewellery piece that is NOT hand-authored in
   jewellery.ts, so the PDP can draw it without waiting for the live catalogue.
   Imported only by JewelDetail, so it rides in the PDP chunk and never in the
   bundle every other page loads. */
import type { JewelPiece } from "@/data/jewellery";

export const jewellerySnapshot: JewelPiece[] = ${JSON.stringify(pieces, null, 2)};
`;
writeFileSync(resolve(process.cwd(), "src/data/jewellerySnapshot.ts"), body);

/* The pre-boot redirect's handle list, from the same response. Only the list
   and the date line change; the file's explanatory header is kept, and the
   one-handle-per-line shape is preserved because the build plugin in
   vite.config.ts parses it. */
const liveHandles = nodes.filter((n) => isJewelleryProduct(n)).map((n) => n.handle).sort();
const handlesPath = resolve(process.cwd(), "src/data/jewelleryHandles.ts");
const handlesSrc = readFileSync(handlesPath, "utf8");
const listed = liveHandles.map((h) => `  "${h}",`).join("\n");
const nextHandles = handlesSrc
  .replace(/new Set\(\[[\s\S]*?\]\);/, `new Set([\n${listed}\n]);`)
  .replace(/Last regenerated [^\n]*/, `Last regenerated ${new Date().toISOString().slice(0, 10)} against the live store: ${liveHandles.length} pieces. */`);
writeFileSync(handlesPath, nextHandles);
console.log(`handle list: ${liveHandles.length} live jewellery handles`);
console.log(`wrote ${pieces.length} pieces (skipped ${known.size} hand-authored)`);
console.log(pieces.map((p) => `  ${p.availableForSale ? " " : "×"} ${p.handle}  ₹${p.price}`).join("\n"));
