/*
  Serve Shopify's canonical product URL, /products/<handle>.

  Every product already has exactly one real page: jewellery at
  /jewellery/<handle>, clothing at /product/<handle> (singular). Both are
  prerendered from the live catalogue by scripts/routes.ts. The plural form is
  the one Shopify itself publishes — it is what the product feed, the Shopify
  catalogue, ads and any pasted admin link use — and nothing served it. Vite's
  SPA fallback answered with the homepage shell, so a shopper following a
  product link landed on the homepage, with the homepage's title and preview
  image, and a crawler saw the same.

  The plural form cannot simply be prerendered: for a jewellery handle the app
  redirects to /jewellery/<handle>, and prerender.ts fails any route that
  redirects — deliberately, because a redirecting route is not a page. So emit
  a redirect stub instead, one per live handle, pointing at whichever real URL
  that product has.

  Driven by the resolved route list rather than a second lookup, so an alias
  cannot outlive the page it points at.
*/

import { mkdirSync, writeFileSync } from "fs";
import { resolve, join } from "path";
import type { SiteRoute } from "./routes";

const DIST = resolve("dist");

/** Real page URL per handle, taken from what was actually prerendered. */
export const targetsFromRoutes = (routes: SiteRoute[]): Map<string, string> => {
  const targets = new Map<string, string>();
  for (const r of routes) {
    const jewel = r.path.match(/^\/jewellery\/([^/]+)$/);
    if (jewel && jewel[1] !== "collections") targets.set(jewel[1], r.path);
    const cloth = r.path.match(/^\/product\/([^/]+)$/);
    if (cloth) targets.set(cloth[1], r.path);
  }
  return targets;
};

const stub = (target: string, origin: string) => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Redirecting…</title>
<link rel="canonical" href="${origin}${target}">
<meta name="robots" content="noindex,follow">
<meta http-equiv="refresh" content="0; url=${target}">
<script>location.replace(${JSON.stringify(target)} + location.search + location.hash);</script>
</head>
<body><p>Redirecting to <a href="${target}">${target}</a>.</p></body>
</html>
`;

/** Writes dist/products/<handle>/index.html for every handle with a real page. */
export const writeProductAliases = (routes: SiteRoute[], origin: string): number => {
  const targets = targetsFromRoutes(routes);
  for (const [handle, target] of targets) {
    const dir = join(DIST, "products", handle);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "index.html"), stub(target, origin), "utf8");
  }
  return targets.size;
};

/*
  Hosts that honour a _redirects file turn these into real 301s, which is
  strictly better: no shell, no JavaScript, no flash. Exact paths only — a
  wildcard here would swallow /products/<handle> for handles that have no page
  and send them somewhere wrong.
*/
export const redirectsBody = (routes: SiteRoute[]): string => {
  const lines = [...targetsFromRoutes(routes)]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([handle, target]) => `/products/${handle}  ${target}  301`);
  return `# Generated by scripts/product-aliases.ts — do not edit by hand.\n` +
    `# Shopify publishes /products/<handle>; the site serves /jewellery/<handle>\n` +
    `# for jewellery and /product/<handle> for clothing.\n${lines.join("\n")}\n`;
};
