// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.27.0";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.27.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/storefront.ts
var STORE_DOMAIN = "nc5eti-gp.myshopify.com";
var API_VERSION = "2025-07";
var STOREFRONT_TOKEN = "0f6fd83502924ac437a5d19180bb08c3";
var PRODUCT_FIELDS = `
  title
  handle
  description
  productType
  tags
  availableForSale
  priceRange { minVariantPrice { amount currencyCode } }
  images(first: 4) { edges { node { url altText } } }
  variants(first: 20) { edges { node { title availableForSale price { amount } } } }
`;
async function storefront(query, variables) {
  const res = await fetch(`https://${STORE_DOMAIN}/api/${API_VERSION}/graphql.json`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Shopify-Storefront-Access-Token": STOREFRONT_TOKEN
    },
    body: JSON.stringify({ query, variables })
  });
  if (!res.ok) throw new Error(`Shopify storefront request failed (${res.status})`);
  const json = await res.json();
  if (json.errors?.length) throw new Error(json.errors[0].message);
  if (!json.data) throw new Error("Shopify returned no data");
  return json.data;
}
function shape(node, withVariants) {
  const images = node.images.edges.filter((e) => (e.node.altText ?? "").trim().toLowerCase() !== "catalog-square").map((e) => e.node.url);
  return {
    handle: node.handle,
    title: node.title,
    description: node.description?.slice(0, withVariants ? 1200 : 240) ?? "",
    productType: node.productType,
    tags: node.tags,
    available: node.availableForSale,
    price: node.priceRange.minVariantPrice.amount,
    currency: node.priceRange.minVariantPrice.currencyCode,
    url: `https://nairaflore.com/products/${node.handle}`,
    image: images[0] ?? node.images.edges[0]?.node.url ?? null,
    ...withVariants ? {
      variants: node.variants.edges.map((e) => ({
        title: e.node.title,
        available: e.node.availableForSale,
        price: e.node.price.amount
      }))
    } : {}
  };
}
async function searchProducts(search, limit) {
  const data = await storefront(
    `query Search($first: Int!, $query: String) {
      products(first: $first, query: $query) { edges { node { ${PRODUCT_FIELDS} } } }
    }`,
    { first: limit, query: search && search.trim() ? search.trim() : void 0 }
  );
  return data.products.edges.map((e) => shape(e.node, false));
}
async function productByHandle(handle) {
  const data = await storefront(
    `query Product($handle: String!) { product(handle: $handle) { ${PRODUCT_FIELDS} } }`,
    { handle }
  );
  return data.product ? shape(data.product, true) : null;
}

// src/lib/mcp/tools/search-products.ts
var search_products_default = defineTool({
  name: "search_products",
  title: "Search Naira Flore pieces",
  description: "Search the live Naira Flore catalogue (jewellery and indo-western pieces) by keyword, returning titles, prices, availability and product links.",
  inputSchema: {
    query: z.string().trim().max(120).optional().describe("Keyword such as 'earrings', 'ring', 'zircone'. Omit to list current pieces."),
    limit: z.number().int().min(1).max(50).default(12).describe("How many pieces to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }) => {
    const products = await searchProducts(query, limit ?? 12);
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.27.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get a piece by handle",
  description: "Fetch full detail for one Naira Flore piece by its product handle, including description, variants, sizes and availability.",
  inputSchema: {
    handle: z2.string().trim().min(1).max(160).describe("Shopify product handle, e.g. 'the-vine-ring'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ handle }) => {
    const product = await productByHandle(handle);
    if (!product) throw new ToolError(`No piece found with handle "${handle}".`);
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/my-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.27.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.112.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/my-profile.ts
var my_profile_default = defineTool3({
  name: "my_profile",
  title: "My member profile",
  description: "Read the signed-in Naira Flore member's profile (name, phone, city, birthday).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("id, full_name, phone, birthday, city").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const profile = data ?? { id: ctx.getUserId(), full_name: null, phone: null, birthday: null, city: null };
    return {
      content: [{ type: "text", text: JSON.stringify({ email: ctx.getUserEmail(), ...profile }, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/tools/my-orders.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.27.0";
import { z as z3 } from "npm:zod@^3.25.76";
var my_orders_default = defineTool4({
  name: "my_orders",
  title: "My orders",
  description: "List the signed-in Naira Flore member's orders, newest first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10).describe("How many orders to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("member_orders").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const orders = data ?? [];
    return {
      content: [
        {
          type: "text",
          text: orders.length ? JSON.stringify(orders, null, 2) : "No orders on this account yet."
        }
      ],
      structuredContent: { orders }
    };
  }
});

// src/lib/mcp/tools/join-inner-circle.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.27.0";
import { z as z4 } from "npm:zod@^3.25.76";
var join_inner_circle_default = defineTool5({
  name: "join_inner_circle",
  title: "Join the Inner Circle",
  description: "Add the signed-in member's email to the Naira Flore Inner Circle list for first access to new collections.",
  inputSchema: {
    name: z4.string().trim().max(80).optional().describe("Name to store with the signup."),
    phone: z4.string().trim().max(20).optional().describe("Optional phone number.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ name, phone }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const email = ctx.getUserEmail();
    if (!email) {
      return { content: [{ type: "text", text: "This account has no email address." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { error } = await supabase.from("inner_circle_signups").insert({
      email,
      name: name ?? null,
      phone: phone ?? null,
      source: "mcp",
      user_id: ctx.getUserId()
    });
    if (error && error.code !== "23505") {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        { type: "text", text: error ? `${email} is already on the Inner Circle list.` : `${email} added to the Inner Circle.` }
      ],
      structuredContent: { email, already: Boolean(error) }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xlsejigpjlqfvzfhhntf";
var mcp_default = defineMcp({
  name: "naira",
  title: "Naira",
  version: "0.1.0",
  instructions: "Tools for Naira Flore, a handcrafted jewellery and indo-western label. Use `search_products` and `get_product` to browse the live catalogue, and `my_profile`, `my_orders` and `join_inner_circle` for the signed-in member's account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, my_profile_default, my_orders_default, join_inner_circle_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.27.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
